#!/bin/bash
# The master install for packages used in each script category

# Packages used in the Utilities Section
echo "Installing packages used in Utilities..."
sudo apt install imagemagick -y
sudo apt-get install ffmpeg -y
